### ISSUE TITLE
something about test my data use pre-trained model

### ISSUE THREAD

**Issue by kirqwer6666** [WeilanAnnn/FD-GAN#8]
### I copy the 0.h5 and 0.jpg in /testsample2 to /facades and use your pretrained model, but i don't know where to find the dehazing image. Or if my procedures were wrong?
==========
```
(fdgan) zyq@zyq:~/桌面/FDGAN$ python demo.py --valDataroot ./facades/0.jpg --netG ./testmodel/netG_epoch_real.pth
Namespace(batchSize=1, beta1=0.5, dataset='pix2pix', display=5, evalIter=500, imageSize=1024, inputChannelSize=3, lrD=0.0002, lrG=0.0002, mode='B2A', netD='', netG='./testmodel/netG_epoch_real.pth', originalSize=1024, outputChannelSize=3, valBatchSize=1, valDataroot='./facades/0.jpg', workers=1)
```
==========
thank you!

**Comment by WeilanAnnn** [comment]
Since the proposed method uses hdf5 file to load the traning samples, the generate_testsample.py helps you to creat the testing or training sample yourself.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WeilanAnnn/FD-GAN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月24日(星期二) 晚上6:00
收件人:&nbsp;"WeilanAnnn/FD-GAN"<FD-GAN@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[WeilanAnnn/FD-GAN] something about test my data use pre-trained model (#8)





 
Hi! sorry to bother you.
 I copy the 0.h5 and 0.jpg in /testsample2 to /facades and use your pretrained model, but i don't know where to find the dehazing image. Or if my procedures were wrong?
 
(fdgan) zyq@zyq:~/桌面/FDGAN$ python demo.py --valDataroot ./facades/0.jpg --netG ./testmodel/netG_epoch_real.pth
 Namespace(batchSize=1, beta1=0.5, dataset='pix2pix', display=5, evalIter=500, imageSize=1024, inputChannelSize=3, lrD=0.0002, lrG=0.0002, mode='B2A', netD='', netG='./testmodel/netG_epoch_real.pth', originalSize=1024, outputChannelSize=3, valBatchSize=1, valDataroot='./facades/0.jpg', workers=1)
 
thank you!
